version: '3.1'

services:
  gobarber_db:
    image: postgres
    container_name: boilerplate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: boilerplate
    ports:
      - 5432:5432

  gobarber_mongo:
    image: mongo
    container_name: boilerplate_mongo
    ports:
      - 27017:27017
  gobarber_redis:
    image: redis:alpine
    container_name: boilerplate_redis
    ports:
      - 6379:6379
